import unittest
import unittest.mock
import io
import sys
from tachyon.core.keys.operations import genesis_ceremony, recovery_drill
from cryptography.hazmat.primitives.asymmetric import ed25519

class TestCeremonyIntegration(unittest.TestCase):
    """
    Integration tests for the Genesis and Recovery ceremonies.
    Mocks user input/output to verify the end-to-end logic round-trip.
    """

    @unittest.mock.patch('builtins.input')
    @unittest.mock.patch('sys.stdout', new_callable=io.StringIO)
    def test_genesis_to_recovery_roundtrip(self, mock_stdout, mock_input):
        """Verify that shares generated by genesis can be used by recover."""
        
        # 1. Simulate Genesis Ceremony
        # Inputs: 'y' for confirmation, then 'Enter' 10 times to reveal/hide 5 shares
        mock_input.side_effect = ['y', '', '', '', '', '', '', '', '', '', '']
        
        genesis_ceremony()
        output = mock_stdout.getvalue()
        
        # Extract shares from output
        shares_found = []
        for line in output.split('\n'):
            if "SHARE" in line and "sss-v1:" in line:
                share_hex = line.split("sss-v1:")[1].strip()
                shares_found.append(share_hex)
        
        self.assertEqual(len(shares_found), 5)
        
        # 2. Simulate Recovery Drill
        # Inputs: paste 3 shares
        mock_input.side_effect = [
            f"sss-v1:{shares_found[0]}",
            f"sss-v1:{shares_found[1]}",
            f"sss-v1:{shares_found[2]}"
        ]
        
        # Clear stdout buffer for recovery part
        mock_stdout.truncate(0)
        mock_stdout.seek(0)
        
        recovery_drill()
        recovery_output = mock_stdout.getvalue()
        
        self.assertIn("SIGN_OK: Reconstruction successful", recovery_output)
        self.assertIn("Derived Fingerprint", recovery_output)

    @unittest.mock.patch('builtins.input')
    @unittest.mock.patch('sys.stdout', new_callable=io.StringIO)
    def test_failed_recovery(self, mock_stdout, mock_input):
        """Verify that incorrect shares lead to a failure message."""
        # 3 random, invalid hex strings
        mock_input.side_effect = [
            "sss-v1:" + "aa"*33,
            "sss-v1:" + "bb"*33,
            "sss-v1:" + "cc"*33
        ]
        
        recovery_drill()
        output = mock_stdout.getvalue()
        # Recovery might fail during reconstruction or during key derivation
        self.assertIn("[✗] RECOVERY FAILED", output)

if __name__ == "__main__":
    unittest.main()
