#!/usr/bin/env python3
"""
Tachyon Tongs: Horizon Scout Submodule
An integrated component of the Sentinel agent that continuously scours the 
open web for competitive intelligence (agentic firewalls, LLM guardrails) and 
feeds structured analysis back into Tachyon's core documentation.
"""

import sys
import os
import asyncio
import json
import datetime

sys.path.append(os.path.join(os.path.dirname(__file__), '..'))
from src.tachyon_client import safe_fetch
from src.metal_accelerator import MetalAccelerator

class HorizonScout:
    def __init__(self):
        self.agent_id = "HorizonScout"
        # High value threat/competitor intelligence feeds
        self.sources = [
            "https://arxiv.org/list/cs.CR/recent", # Crypto and Security
            "https://arxiv.org/list/cs.AI/recent", # AI
            "https://owasp.org/www-project-top-10-for-llm-applications/"
        ]
        
    def scour_web(self):
        """
        Executes outbound fetches through the Guardian Triad.
        Returns the sanitized text of all successful intelligence pulls.
        """
        print(f"[{datetime.datetime.now().isoformat()}] Horizon Scout initiating web scour...")
        raw_intelligence = []
        
        for url in self.sources:
            print(f"  -> Pulling {url}")
            # Route through the Triad to prevent the Scout from hitting a poisoned honeypot
            result = safe_fetch(url, agent_id=self.agent_id)
            
            if result.get("status") == "SUCCESS":
                content = result.get("result", {}).get("content", "")
                # We only keep a snippet of text to avoid blowing up the context window later
                raw_intelligence.append(f"Source: {url}\nContent preview: {content[:1500]}\n")
            else:
                print(f"  -> [BLOCKED] Triad prevented ingestion of {url}")

        return "\n---\n".join(raw_intelligence)
        
    def analyze_and_persist(self, raw_intel: str):
        """Passes the raw intel into the Air-Gapped MLX Analyst and persists the results."""
        if not raw_intel.strip():
            print("  -> No new intelligence gathered. Aborting analysis.")
            return

        print(f"[{datetime.datetime.now().isoformat()}] Horizon Scout initiating LLM Epistemic Analysis...")
        results = MetalAccelerator.analyze_competitive_intel(raw_intel)
        
        if "error" in results:
            print(f"[ERROR] Analyst Failed: {results['error']}")
            return

        analysis = results.get("competitive_analysis")
        tasks = results.get("actionable_plan")
        
        base_dir = os.path.dirname(__file__)
        
        if analysis:
            docs_path = os.path.join(base_dir, '..', 'docs', 'COMPETITIVE_ANALYSIS.md')
            with open(docs_path, 'w') as f:
                f.write("# Tachyon Tongs: Competitive Analysis & Market Positioning\n\n*Auto-Generated by Horizon Scout*\n\n" + analysis)
            print(f"  -> Successfully updated docs/COMPETITIVE_ANALYSIS.md")
            
        if tasks:
            strategy_path = os.path.join(base_dir, '..', 'PENDING_STRATEGY_MERGE.md')
            with open(strategy_path, 'w') as f:
                f.write("# [PENDING REVIEW] Horizon Scout Strategic Roadmap\n\n" 
                        "The following actionable metrics were reverse-engineered from competitor intel.\n"
                        "Please move these into `TASKS.md` and `docs/ROADMAP.md` manually if you agree with the direction.\n\n" + tasks)
            print(f"  -> Successfully drafted PENDING_STRATEGY_MERGE.md for human review")

if __name__ == "__main__":
    scout = HorizonScout()
    intel = scout.scour_web()
    if intel:
        scout.analyze_and_persist(intel)
